# Generated by Django 6.0.2 on 2026-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.DateTimeField(auto_now_add=True)),
                ('predicted_hour', models.DateTimeField(blank=True, null=True)),
                ('arima_price', models.FloatField()),
                ('lr_price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-logged_time'],
            },
        ),
    ]
