# Generated by Django 4.2.29 on 2026-03-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InferenceHistory',
        ),
    ]
